# Generated by Django 5.2.4 on 2026-04-24 09:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_auto_20250812_0724"),
    ]

    operations = [
        migrations.CreateModel(
            name="PackagePolicy",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="정책명", max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "활성"), ("INACTIVE", "비활성")], default="ACTIVE", max_length=20
                    ),
                ),
                (
                    "min_items",
                    models.PositiveIntegerField(
                        default=2, help_text="최소 구성 수량", validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "max_items",
                    models.PositiveIntegerField(
                        default=5, help_text="최대 구성 수량", validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("allow_duplicate_items", models.BooleanField(default=False, help_text="같은 상품 중복 허용 여부")),
                (
                    "allowed_item_scope",
                    models.CharField(
                        choices=[
                            ("ALL_PRODUCTS", "모든 상품"),
                            ("SINGLE_PRODUCTS", "단일 상품만"),
                            ("PACKAGE_PRODUCTS", "패키지 상품만"),
                            ("ALLOWED_SET", "허용 상품만"),
                        ],
                        default="SINGLE_PRODUCTS",
                        help_text="허용 상품 범위",
                        max_length=30,
                    ),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("NONE", "없음"), ("FIXED_AMOUNT", "정액 할인")], default="NONE", max_length=20
                    ),
                ),
                ("discount_value", models.PositiveIntegerField(default=0, help_text="할인 금액")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "package_policies",
            },
        ),
        migrations.CreateModel(
            name="PackagePolicyAllowedProduct",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "package_policy_allowed_products",
            },
        ),
        migrations.AlterModelOptions(
            name="packageitem",
            options={"ordering": ["sort_order", "id"]},
        ),
        migrations.AddField(
            model_name="packageitem",
            name="quantity",
            field=models.PositiveIntegerField(
                default=1, help_text="구성 수량", validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AddField(
            model_name="packageitem",
            name="sort_order",
            field=models.PositiveIntegerField(default=0, help_text="노출 순서"),
        ),
        migrations.AlterField(
            model_name="packageitem",
            name="drink",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="package_items", to="products.drink"
            ),
        ),
        migrations.AlterField(
            model_name="packageitem",
            name="package",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="items", to="products.package"
            ),
        ),
        migrations.AddIndex(
            model_name="packageitem",
            index=models.Index(fields=["package", "sort_order"], name="package_ite_package_4603b9_idx"),
        ),
        migrations.AddIndex(
            model_name="packageitem",
            index=models.Index(fields=["drink"], name="package_ite_drink_i_055789_idx"),
        ),
        migrations.AddField(
            model_name="package",
            name="policy",
            field=models.ForeignKey(
                blank=True,
                help_text="패키지 적용 정책",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="packages",
                to="products.packagepolicy",
            ),
        ),
        migrations.AddField(
            model_name="packagepolicyallowedproduct",
            name="policy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="allowed_product_items",
                to="products.packagepolicy",
            ),
        ),
        migrations.AddField(
            model_name="packagepolicyallowedproduct",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="allowed_package_policy_items",
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="packagepolicy",
            name="allowed_products",
            field=models.ManyToManyField(
                blank=True,
                related_name="package_policies",
                through="products.PackagePolicyAllowedProduct",
                to="products.product",
            ),
        ),
        migrations.AddIndex(
            model_name="packagepolicyallowedproduct",
            index=models.Index(fields=["policy"], name="package_pol_policy__c87ce2_idx"),
        ),
        migrations.AddIndex(
            model_name="packagepolicyallowedproduct",
            index=models.Index(fields=["product"], name="package_pol_product_96072c_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="packagepolicyallowedproduct",
            unique_together={("policy", "product")},
        ),
        migrations.AddIndex(
            model_name="packagepolicy",
            index=models.Index(fields=["status"], name="package_pol_status_af9b4a_idx"),
        ),
        migrations.AddIndex(
            model_name="packagepolicy",
            index=models.Index(fields=["allowed_item_scope"], name="package_pol_allowed_05dd15_idx"),
        ),
    ]
