# Generated by Django 5.2.4 on 2026-04-24 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_packagepolicy_packagepolicyallowedproduct_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="package",
            name="type",
            field=models.CharField(
                choices=[("CURATED", "큐레이티드")], default="CURATED", help_text="패키지 타입", max_length=10
            ),
        ),
    ]
