# Generated by Codex on 2026-04-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_alter_package_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_tasting_available",
            field=models.BooleanField(default=False, help_text="시음 가능 여부"),
        ),
    ]
