# Generated by Django 5.2.4 on 2026-05-07 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_product_is_tasting_available"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="is_award_winning",
        ),
        migrations.RemoveField(
            model_name="product",
            name="is_gift_suitable",
        ),
        migrations.RemoveField(
            model_name="product",
            name="is_limited_edition",
        ),
        migrations.RemoveField(
            model_name="product",
            name="is_organic",
        ),
        migrations.RemoveField(
            model_name="product",
            name="is_premium",
        ),
        migrations.RemoveField(
            model_name="product",
            name="is_regional_specialty",
        ),
        migrations.CreateModel(
            name="ProductTag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="태그명", max_length=50, unique=True)),
                ("slug", models.SlugField(help_text="태그 식별자", max_length=80, unique=True)),
                (
                    "group",
                    models.CharField(
                        choices=[("DISPLAY", "노출"), ("RECOMMENDATION", "추천"), ("FEATURE", "특성")],
                        default="FEATURE",
                        help_text="태그 그룹",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, help_text="태그 설명")),
                ("is_active", models.BooleanField(default=True, help_text="활성 여부")),
                ("sort_order", models.PositiveIntegerField(default=0, help_text="정렬 순서")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "product_tags",
                "ordering": ["sort_order", "name"],
                "indexes": [
                    models.Index(fields=["slug"], name="product_tag_slug_8a0b27_idx"),
                    models.Index(fields=["group", "is_active"], name="product_tag_group_e8240c_idx"),
                    models.Index(fields=["sort_order"], name="product_tag_sort_or_01780c_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProductTagging",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="taggings", to="products.product"
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="taggings", to="products.producttag"
                    ),
                ),
            ],
            options={
                "db_table": "product_taggings",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="products", through="products.ProductTagging", to="products.producttag"
            ),
        ),
        migrations.AddIndex(
            model_name="producttagging",
            index=models.Index(fields=["product"], name="product_tag_product_545821_idx"),
        ),
        migrations.AddIndex(
            model_name="producttagging",
            index=models.Index(fields=["tag"], name="product_tag_tag_id_01a570_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="producttagging",
            unique_together={("product", "tag")},
        ),
    ]
