# Generated by Django 5.2.4 on 2026-05-07 08:40

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0007_remove_feedback_negative_tags_and_positive_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="acidity",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="산미가 내 입맛에 맞은 정도 (0.0-5.0)",
                max_digits=3,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.0")),
                    django.core.validators.MaxValueValidator(Decimal("5.0")),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="aroma",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="향이 내 입맛에 맞은 정도 (0.0-5.0)",
                max_digits=3,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.0")),
                    django.core.validators.MaxValueValidator(Decimal("5.0")),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="bitterness",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="쓴맛이 내 입맛에 맞은 정도 (0.0-5.0)",
                max_digits=3,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.0")),
                    django.core.validators.MaxValueValidator(Decimal("5.0")),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="body",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="바디감이 내 입맛에 맞은 정도 (0.0-5.0)",
                max_digits=3,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.0")),
                    django.core.validators.MaxValueValidator(Decimal("5.0")),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="carbonation",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="탄산감이 내 입맛에 맞은 정도 (0.0-5.0)",
                max_digits=3,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.0")),
                    django.core.validators.MaxValueValidator(Decimal("5.0")),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="sweetness",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="단맛이 내 입맛에 맞은 정도 (0.0-5.0)",
                max_digits=3,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.0")),
                    django.core.validators.MaxValueValidator(Decimal("5.0")),
                ],
            ),
        ),
    ]
