# Generated by Django 5.2.4 on 2026-05-07 08:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0008_alter_feedback_acidity_alter_feedback_aroma_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="confidence",
            field=models.PositiveIntegerField(
                default=50,
                help_text="내부 학습 신뢰도 기본값 (0-100%)",
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)],
            ),
        ),
    ]
