# Generated by Django 5.2.4 on 2026-05-07 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0009_alter_feedback_confidence"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="feedback",
            name="feedbacks_sweetne_d7f71f_idx",
        ),
        migrations.RemoveIndex(
            model_name="feedback",
            name="feedbacks_carbona_778c82_idx",
        ),
        migrations.RemoveField(
            model_name="feedback",
            name="acidity",
        ),
        migrations.RemoveField(
            model_name="feedback",
            name="aroma",
        ),
        migrations.RemoveField(
            model_name="feedback",
            name="bitterness",
        ),
        migrations.RemoveField(
            model_name="feedback",
            name="body",
        ),
        migrations.RemoveField(
            model_name="feedback",
            name="carbonation",
        ),
        migrations.RemoveField(
            model_name="feedback",
            name="confidence",
        ),
        migrations.RemoveField(
            model_name="feedback",
            name="selected_tags",
        ),
        migrations.RemoveField(
            model_name="feedback",
            name="sweetness",
        ),
    ]
