# Generated by Django 5.2.4 on 2026-04-24 09:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0008_packagedraft_packagedraftitem_and_more"),
        ("orders", "0003_remove_orderitem_gift_message_and_more"),
        ("products", "0007_alter_package_type"),
        ("stores", "0006_alter_storelike_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderCustomPackage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("display_name", models.CharField(max_length=80)),
                ("package_policy_name", models.CharField(max_length=50)),
                ("base_price", models.PositiveIntegerField(help_text="구성품 합산가")),
                ("discount_amount", models.PositiveIntegerField(default=0, help_text="정책 할인 금액")),
                ("final_price", models.PositiveIntegerField(help_text="최종 패키지 가격")),
                ("pickup_day", models.DateField(help_text="픽업 예정 날짜")),
                ("pickup_status", models.BooleanField(default=False, help_text="픽업 완료 여부")),
                ("is_tasting_selected", models.BooleanField(default=False, help_text="시음 선택 여부")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="custom_packages", to="orders.order"
                    ),
                ),
                (
                    "pickup_store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_custom_packages",
                        to="stores.store",
                    ),
                ),
                (
                    "source_draft",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_snapshots",
                        to="cart.packagedraft",
                    ),
                ),
            ],
            options={
                "db_table": "order_custom_packages",
            },
        ),
        migrations.CreateModel(
            name="OrderCustomPackageItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("product_name", models.CharField(max_length=100)),
                ("price", models.PositiveIntegerField(help_text="주문 당시 상품 단가")),
                ("quantity", models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "custom_package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.ordercustompackage",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_custom_package_items",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "db_table": "order_custom_package_items",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="ordercustompackage",
            index=models.Index(fields=["order"], name="order_custo_order_i_f7df5b_idx"),
        ),
        migrations.AddIndex(
            model_name="ordercustompackage",
            index=models.Index(fields=["pickup_store"], name="order_custo_pickup__d6484f_idx"),
        ),
        migrations.AddIndex(
            model_name="ordercustompackage",
            index=models.Index(fields=["pickup_day"], name="order_custo_pickup__20345c_idx"),
        ),
        migrations.AddIndex(
            model_name="ordercustompackage",
            index=models.Index(fields=["pickup_status"], name="order_custo_pickup__3deb39_idx"),
        ),
        migrations.AddIndex(
            model_name="ordercustompackageitem",
            index=models.Index(fields=["custom_package", "sort_order"], name="order_custo_custom__040342_idx"),
        ),
        migrations.AddIndex(
            model_name="ordercustompackageitem",
            index=models.Index(fields=["product"], name="order_custo_product_8dbde9_idx"),
        ),
    ]
