# Generated by Django 5.2.4 on 2026-05-08 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_ordercustompackage_ordercustompackageitem_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("provider", models.CharField(choices=[("TEST", "테스트 결제")], default="TEST", max_length=20)),
                ("payment_key", models.CharField(blank=True, help_text="PG 결제 식별자", max_length=120)),
                ("merchant_uid", models.CharField(help_text="내부 결제 주문번호", max_length=80, unique=True)),
                ("amount", models.PositiveIntegerField(help_text="결제 금액")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("READY", "결제 대기"),
                            ("PAID", "결제 완료"),
                            ("FAILED", "결제 실패"),
                            ("CANCELLED", "결제 취소"),
                            ("REFUNDED", "환불 완료"),
                        ],
                        default="READY",
                        max_length=20,
                    ),
                ),
                ("is_test_payment", models.BooleanField(default=True, help_text="테스트 결제 여부")),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("raw_response", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "payments",
            },
        ),
        migrations.AddField(
            model_name="order",
            name="fulfillment_method",
            field=models.CharField(
                choices=[("PICKUP", "매장 수령"), ("DELIVERY", "배송"), ("UNDECIDED", "미정")],
                default="PICKUP",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="is_test_order",
            field=models.BooleanField(default=True, help_text="테스트 결제 주문 여부"),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("READY", "결제 대기"),
                    ("PAID", "결제 완료"),
                    ("FAILED", "결제 실패"),
                    ("CANCELLED", "결제 취소"),
                    ("REFUNDED", "환불 완료"),
                ],
                default="READY",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING_PAYMENT", "결제 대기"),
                    ("PENDING", "주문 완료"),
                    ("CONFIRMED", "주문 확인"),
                    ("READY", "픽업 준비 완료"),
                    ("COMPLETED", "픽업 완료"),
                    ("CANCELLED", "주문 취소"),
                ],
                default="PENDING_PAYMENT",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["payment_status"], name="orders_payment_050188_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["fulfillment_method"], name="orders_fulfill_abc31d_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["is_test_order"], name="orders_is_test_eace0c_idx"),
        ),
        migrations.AddField(
            model_name="payment",
            name="order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name="payment", to="orders.order"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["order"], name="payments_order_i_b32b33_idx"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["merchant_uid"], name="payments_merchan_75f493_idx"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["status"], name="payments_status_d621e5_idx"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["is_test_payment"], name="payments_is_test_6b9484_idx"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["-created_at"], name="payments_created_26b056_idx"),
        ),
    ]
