# Generated by Django 5.2.4 on 2026-05-08 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_payment_order_fulfillment_method_order_is_test_order_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="provider",
            field=models.CharField(
                choices=[("TEST", "테스트 결제"), ("TOSS_TEST", "토스페이먼츠 테스트 결제")],
                default="TEST",
                max_length=20,
            ),
        ),
    ]
