# Generated by Django 5.2.4 on 2026-05-10 05:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_alter_payment_provider"),
        ("stores", "0006_alter_storelike_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="pickup_day",
            field=models.DateField(blank=True, help_text="주문 단위 픽업 예정 날짜", null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="pickup_store",
            field=models.ForeignKey(
                blank=True,
                help_text="주문 단위 픽업 매장",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders_for_pickup",
                to="stores.store",
            ),
        ),
        migrations.AlterField(
            model_name="ordercustompackage",
            name="pickup_day",
            field=models.DateField(blank=True, help_text="픽업 예정 날짜", null=True),
        ),
        migrations.AlterField(
            model_name="ordercustompackage",
            name="pickup_store",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_custom_packages",
                to="stores.store",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="pickup_day",
            field=models.DateField(blank=True, help_text="픽업 예정 날짜", null=True),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="pickup_store",
            field=models.ForeignKey(
                blank=True,
                help_text="픽업 매장",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_items",
                to="stores.store",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["pickup_store"], name="orders_pickup__6b3fa5_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["pickup_day"], name="orders_pickup__1926ef_idx"),
        ),
    ]
