# Generated by Django 5.2.4 on 2026-04-24 09:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0007_alter_cartitem_unique_together"),
        ("products", "0007_alter_package_type"),
        ("stores", "0006_alter_storelike_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PackageDraft",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("display_name", models.CharField(help_text="사용자에게 표시할 패키지명", max_length=80)),
                ("base_price", models.PositiveIntegerField(default=0, help_text="구성품 합산가")),
                ("discount_amount", models.PositiveIntegerField(default=0, help_text="정책 할인 금액")),
                ("final_price", models.PositiveIntegerField(default=0, help_text="최종 패키지 가격")),
                (
                    "status",
                    models.CharField(
                        choices=[("DRAFT", "작성 중"), ("READY", "주문 가능"), ("ORDERED", "주문 완료")],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("pickup_date", models.DateField(blank=True, help_text="픽업 날짜", null=True)),
                ("is_tasting_selected", models.BooleanField(default=False, help_text="시음 선택 여부")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pickup_store",
                    models.ForeignKey(
                        blank=True,
                        help_text="픽업 매장",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="package_drafts_for_pickup",
                        to="stores.store",
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="package_drafts",
                        to="products.packagepolicy",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="package_drafts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "package_drafts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PackageDraftItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1, help_text="구성 수량", validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0, help_text="노출 순서")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "draft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="items", to="cart.packagedraft"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="package_draft_items",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "db_table": "package_draft_items",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="packagedraft",
            index=models.Index(fields=["user", "status"], name="package_dra_user_id_3f9432_idx"),
        ),
        migrations.AddIndex(
            model_name="packagedraft",
            index=models.Index(fields=["policy"], name="package_dra_policy__b9b30e_idx"),
        ),
        migrations.AddIndex(
            model_name="packagedraft",
            index=models.Index(fields=["created_at"], name="package_dra_created_8ff6cf_idx"),
        ),
        migrations.AddIndex(
            model_name="packagedraftitem",
            index=models.Index(fields=["draft", "sort_order"], name="package_dra_draft_i_c1572c_idx"),
        ),
        migrations.AddIndex(
            model_name="packagedraftitem",
            index=models.Index(fields=["product"], name="package_dra_product_30ff27_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="packagedraftitem",
            unique_together={("draft", "product")},
        ),
    ]
